config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :lockers do
    resources :bookings
  end

  get '/my_lockers', to: 'pages#my_lockers'
  get '/my_bookings', to: 'pages#my_bookings'
  get '/profile', to: 'pages#profile'
  delete '/my_bookings', to: 'bookings#destroy', as: 'my_bookings_destroy'
end

#comentenando mais

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :locker
  validates :user, uniqueness: { scope: :locker }
end

app/models/locker.rb
class Locker < ApplicationRecord

  belongs_to :user


  validates :address, presence: true
  validates :size, presence: true, inclusion: { in: ['S - W40 | H40 | 40cm','M - W70 | H40 | 70cm','L - W90 | H60 | 90cm'] }
  validates :price, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?


  def get_photo
    if size == 'S - W40 | H40 | 40cm'
      photo = "https://www.3dlockers.co.uk/_assets/img/site/products/large/3-door.jpg"
    elsif size == 'M - W70 | H40 | 70cm'
      photo = "https://www.3dlockers.co.uk/_assets/img/site/products/large/small-chemical-coshh-cabinet-900-x-460-x-460.jpg"
    else
      photo = "https://www.3dlockers.co.uk/_assets/img/site/products/large/1800high-security-cupboard.jpg"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :lockers
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, :except => :index, unless: :devise_controller?
  after_action :verify_policy_scoped, :only => :index, unless: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
  class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
    @bookings = policy_scope(Booking).order(created_at: :desc)
  end

  def show
    @booking = Booking.find(booking_params)
    authorize @booking
  end

  def edit
    @booking = Booking.find(params[:id])
    @locker = Locker.find(params[:locker_id])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    authorize @booking
    redirect_to my_bookings_path
  end

  def destroy
    @booking = Booking.where(user_id: current_user.id).first
    authorize @booking
    @booking.destroy
    redirect_to my_bookings_destroy_path
  end

 def create
    @booking = Booking.new(booking_params)

    @locker = Locker.find(params[:locker_id])
    @booking.locker = @locker
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to my_bookings_path, notice: 'Booking was successfully created.'
    else
      render 'lockers/show'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :start_time, :end_time, :locker_id)
  end
end

app/controllers/lockers_controller.rb
class LockersController < ApplicationController
  before_action :set_locker, only: [ :edit, :update, :destroy]

  def index
    #@lockers = Locker.geocoded

    if params[:search].present? && params[:search][:query].present?
      @lockers = policy_scope(Locker).where("address ILIKE '%#{params[:search][:query]}%'").geocoded
    else
      @lockers = policy_scope(Locker).order(created_at: :desc).geocoded
    end

    @markers = @lockers.map do |locker|
      {
        lat: locker.latitude,
        lng: locker.longitude
      }
    end
  end

  def show
    @locker = Locker.geocoded.find(params[:id])
    authorize @locker
    @booking = Booking.new
    @markers =
      {
        lat: @locker.latitude,
        lng: @locker.longitude
      }
  end

  def new
    @locker = current_user.lockers.new
    authorize @locker
  end

  def create
    @locker = current_user.lockers.new(locker_params)
    @locker.photo = @locker.get_photo
    @locker.user_id = current_user.id
    authorize @locker
    if @locker.save # => false / true
      redirect_to lockers_path, notice: 'Locker was successfully created!'
    else
      render :new
      puts @locker.errors.messages
    end
  end

  def edit
    authorize @locker
  end

  def update
    authorize @locker
    if @locker.update(locker_params)
      @locker.photo = @locker.get_photo
      @locker.save
      redirect_to locker_path(@locker)
    else
      puts @locker.errors.messages
      render :edit
    end
  end

  def destroy
    authorize @locker
    if @locker.destroy
      redirect_to my_lockers_path, notice: "Locker was successfully destroyed"
    else
      puts @locker.errors.messages
    end
  end

  private

  def locker_params
    params.require(:locker).permit(:size, :price, :address, :photo)
  end

  def set_locker
    @locker = Locker.find(params[:id])
  end
end
#quasre

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home
  skip_after_action :verify_authorized, only: :home

  def home
    @lockers = policy_scope(Locker).order(created_at: :desc)
  end

  def my_bookings
    @bookings = current_user.bookings #policy_scope(Booking)
    authorize @bookings
  end

  def my_lockers
    @lockers = current_user.lockers
    authorize @lockers
  end

  def profile
    @user = current_user
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container">
  <br>
  <h3> Update my booking </h3>
</div>

  <div class="col-sm-12 col-lg-6">
      <div class="d-flex justify-content-between">
          <%= simple_form_for [@locker, @booking], method: :patch do |f| %>
        <div class="d-flex">
          <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.input :start_time, as: :string, required: false, input_html: {class: "timepicker"} %>
        </div>
        <div class="d-flex justify-content-between">
          <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.input :end_time, as: :string, required: false, input_html: {class: "timepicker"} %>
        </div>
          <%= f.button :submit, "Change", class: "btn btn-flat" %>
          <% end %>
      </div>
  </div>

app/views/bookings/index.html.erb
<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Start date</th>
        <th scope="col">End date</th>
        <th scope="col">Address</th>
        <th scope="col">Price</th>
      </tr>
    </thead>

    <tbody>
      <% count = 1 %>
      <% @bookings.each do |booking| %>
        <tr>
          <th scope="row"><%= count %></th>
          <td> <%= booking.start_date %> </td>
          <td> <%= booking.end_date %> </td>
          <td> <%= booking.locker.address %></td>
          <td> <%= booking.locker.price %> €/h </td>
        </tr>
        <% count += 1 %>

      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>loca-locker</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/nav-bar' %>
    <%= yield %>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/layouts/footer.html.erb
<div class=" footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
<!--   <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at loca-locker
  </div>
</div> -->

app/views/lockers/_info_window.html.erb
<p><%= locker.address %></p>

app/views/lockers/edit.html.erb
<div class="container">
  <br>
  <h3>Edit locker</h3>
  <br>
  <%= simple_form_for @locker do |f| %>
    <%= f.input :address %>
    <%= f.input :size, collection: ['S - W40 | H40 | 40cm','M - W70 | H40 | 70cm','L - W90 | H60 | 90cm'] %>
    <%= f.input :price, label: 'Price per hour', input_html: {min: "1"}%>
    <%= f.button :submit, class: "btn btn-flat" %>
  <% end %>
</div>

app/views/lockers/index.html.erb
<head>
<title>new Loca Lockers index</title>
</head>


  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-6" id="card-index">
      <div class="cards">
      <%= render 'shared/card' %>
    </div>
  </div>
    <div class="col-sm-12 col-lg-6">
      <div
        id="map"
        style="width: 98%;
        height: 600px;
        margin-top: 37px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
<!--       <div class="sidemap">
        <div
          id="map"
          style="width: 100%;
          height: 800px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div> -->
      </div>
  </div>
</div>

app/views/lockers/new.html.erb
<div class="container">
  <br>
    <h1>Add locker</h1>
    <br>
  <%= simple_form_for @locker do |f| %>
    <%= f.input :address %>
    <%= f.input :size, collection: ['S - W40 | H40 | 40cm','M - W70 | H40 | 70cm','L - W90 | H60 | 90cm'] %>
    <%= f.input :price, label: 'Price per hour', input_html: {min: "1"}%>
    <%= f.button :submit,"Add Locker", class: "btn btn-flat" %>
<% end %>

</div>

app/views/lockers/show.html.erb
<div class="container" id="show">
  <div class="row">
    <div class="col-lg-6">
      <div class="card" style="width: 100%;">
        <%= image_tag @locker.photo, class: 'card-img-top' %>
        <div class="card-body">
              <h5 class="card-title">
                <%= @locker.address %>
              </h5>
              <h6> Size:
                <%= @locker.size %>
              </h6>
              <p class="card-text">
                Price:
               <%= @locker.price %> €/h
              </p>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-lg-6">
        <div class="d-flex justify-content-between">
          <%= simple_form_for [@locker, @booking], method: "post" do |f| %>
          <div class="d-flex">
            <div id="hora">
            <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
            </div>
            <%= f.input :start_time, as: :string, required: false, input_html: {class: "timepicker"} %>
            </div>
            <div class="d-flex justify-content-between">
              <div id="hora">
            <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
            </div>
            <%= f.input :end_time, as: :string, required: false, input_html: {class: "timepicker"} %>
            </div>
            <%= f.button :submit, "Reserve", class: "btn btn-flat" %>
          <% end %>
        </div>
              <div
  id="map"
  style="width: 100%;
  height: 475px;
  margin-top: 20px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>
    </div>

app/views/pages/home.html.erb
<head>
  <title>Loca Lockers</title>
</head>

<%= render 'shared/banner' %>
<div class="cards">
  <%= render 'shared/card' %>
</div>

app/views/pages/my_bookings.html.erb
<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Start date</th>
        <th scope="col">End date</th>
        <th scope="col">Address</th>
        <th scope="col">Price</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>

    <tbody>
      <% count = 1 %>
      <% @bookings.each do |booking| %>
        <tr>
          <th scope="row"><%= count %></th>
          <td> <%= booking.start_date %>
               <%= booking.start_time %></td>
          <td> <%= booking.end_date %>
               <%= booking.end_time %></td>
          <td> <%= booking.locker.address %></td>
          <td> <%= booking.locker.price %> €/h </td>
          <td><%= link_to "Edit", edit_locker_booking_path(booking.locker_id, booking.id), class: "btn btn-flat" %></td>
          <td><%= link_to "Delete", my_bookings_destroy_path, method: :delete, class: "btn btn-flat" %></td>
        </tr>
        <% count += 1 %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/pages/my_lockers.html.erb
<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Address</th>
        <th scope="col">Size</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>

    <tbody>
      <% count = 1 %>
      <% @lockers.each do |locker| %>
        <tr>
          <th scope="row"><%= count %></th>
          <td><%= locker.address %> </td>
          <td><%= locker.size %> </td>
          <td><%= link_to "Edit", edit_locker_path(locker), class: "btn btn-flat" %></td>
          <td><%= link_to "Delete", locker, method: :delete, class: "btn btn-flat" %></td>
        </tr>
        <% count += 1 %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/pages/profile.html.erb
<div class="container">
  <br />
  <br />
  <div class="row">
    <div class="col-md-3">
      <div class="text-center">
        <%= image_tag "https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1580586175/ntpyaym6fuq3mq3ktv3t.jpg" %>
      </div>
    </div>

    <div class="col-md-9 personal-info">
      <h5><b>Your Details</b></h5>
      <br />
      <form class="form-horizontal" role="form">
        <div class="form-group">
          <p><u>First Name</u></p>
          <%= current_user.first_name %>
        </div>
        <hr>

        <div class="form-group">
          <p><u>Last Name</u></p>
          <%= current_user.last_name %>
        </div>
        <hr>

        <div class="form-group">
          <p><u>Email</u></p>
          <%= current_user.email %>
        </div>
        <br />

        <div class="form-group">
            <a href="users/edit" class="btn btn-flat" role="button"><strong>Edit Details</strong></a>
        </div>
      </form>
    </div>
  </div>
</div>
<hr>

app/views/shared/_alert.html.erb
<div class="flash flash-success alert alert-dismissible fade show" role="alert">
  <span><strong>Yay!</strong> 🎉 you successfully signed in to our service.</span>
  <a data-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>

<div class="flash flash-warning alert alert-dismissible fade show" role="alert">
  <span><strong>Mmh</strong> 🤔 seems like you don't have <a href="#">logged</a> yet.</span>
  <a data-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>

<div class="flash flash-danger alert alert-dismissible fade show" role="alert">
  <span><strong>Oops!</strong> 😱 a problem has occurred while processing your booking.</span>
  <a data-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>

app/views/shared/_avatar.html.erb
<img class="avatar" alt="avatar" src="https://kitt.lewagon.com/placeholder/users/cveneziani" />
<img class="avatar-large" alt="avatar-large" src="https://kitt.lewagon.com/placeholder/users/arthur-littm" />
<img class="avatar-bordered" alt="avatar-bordered" src="https://kitt.lewagon.com/placeholder/users/sarahlafer" />
<img class="avatar-square" alt="avatar-square" src="https://kitt.lewagon.com/placeholder/users/krokrob" />

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(https://www.urbanparkgru.com.br/dicas-de-viagem/wp-content/uploads/2019/05/amazon-locker.png);">
  <div class="container">
    <h1 id="banner">Store Your Bags With A Few Clicks</h1>
    <p>Search For A Luggage Storage Location Near You</p>
    <%= render 'shared/search_form' %>
  </div>
</div>

app/views/shared/_button.html.erb
<%= link_to "Write a story", "#", class: "btn btn-ghost" %>
<%= link_to "Book now", "#", class: "btn btn-flat" %>
<%= link_to "Start now", "#", class: "btn btn-gradient" %>

app/views/shared/_card-trip.html.erb
<div class="card-trip">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
  <div class="card-trip-infos">
    <div>
      <h2><%= locker.address %></h2>
      <p><%= locker.size %></p>
    </div>
    <h2 class="card-trip-pricing"><%= locker.price %> €/h</h2>
  </div>
</div>

app/views/shared/_card.html.erb
<% @lockers.each do |locker| %>
  <%= link_to locker_path(locker) do %>
  <div class="card-category" id="small-locker" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url(<%= locker.photo %>)">
    <div class="d-flex justify-content-sm-center flex-column ">
      <h5><%= locker.address %></h5>
      <p><%= locker.price %> €/h</p>
      <p><%= locker.size %></p>
    </div>
  </div>
  <% end %>
  <% end %>

app/views/shared/_footer.html.erb
<div class="d-flex justify-content-center footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
<!--   <div class="Flex-end row">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div> -->
</div>
<br>

app/views/shared/_nav-bar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
    <%= link_to root_path do %>
    <%= image_tag "https://res.cloudinary.com/dwppwrimk/image/upload/v1582901964/loca_locker_10_ew4rpo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

    <% if user_signed_in? %>

      <li class="nav-item dropdown">
        <%= image_tag "https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1580586175/ntpyaym6fuq3mq3ktv3t.jpg", class: "avatar", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Profile", profile_path, class: "dropdown-item" %>
          <%= link_to "My Bookings", my_bookings_path, class: "dropdown-item" %>
          <%= link_to "My Lockers", my_lockers_path, class: "dropdown-item" %>
          <%= link_to "Add Locker", new_locker_path, class: "dropdown-item" %>
          <%= link_to "Logout", destroy_user_session_path,  method: :delete, class: "dropdown-item" %>
        </div>
      </li>

        <% else %>

        <li class="nav-item">
        <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
      </li>
    <% end %>
    </ul>
  </div>
</div>

</div>

app/views/shared/_search_form.html.erb
<%= simple_form_for :search, url: lockers_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="Location"/>
    <button name="button" type="submit" class="btn btn-flat">
      Search
    </button>
  </div>
<% end %>